### ISSUE TITLE
Where can I print the decoding time?

### ISSUE THREAD

**Issue by ichlubna** [RenYang-home/ALVC#3]
The paper contains the measured decoding time. Where do I need to add the timer in your code to measure how long does one frame take to decode?
Thanks for sharing the code by the way! It's functional and easy to use.

**Comment by RenYang-home** [comment]
Sorry for the late reply.

For the decoding time of P-frames, please evaluate the time of the following three lines in the codes:

Recurrent_Autoencoder_Extrapolation.py Line 185
Extrapolation.py Line 87
Recurrent_Prob_Model.py Line 109

For B-frames, the decoding time is the the time of Line 172 in Interpolation_Compression.py 

Please feel free to contact me for any further questions.

**Comment by ichlubna** [comment]
Many thanks @RenYang-home!!!
